### PR TITLE
USF-1327: Checkout containers

### PR DESCRIPTION
**Pull request by jeff-matthews**
This pull request (PR) documents Checkout container configuration options based on the [doc template](https://github.com/commerce-docs/microsite-commerce-storefront/blob/develop/_dropin-templates/dropin-containers.mdx?plain=1) for dropin containers.

Options and descriptions are based on the prop interfaces defined for each component in the source code. 

## TODO

- [x] Articulate potential/practical use case(s) for each container
- [ ] Provide an example configuration that covers all containers
- [ ] Provide an example of configuring options on a container w/ before and after screenshot of boilerplate and modified boilerplate

## Review build

_TBD_

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@bdenham & @keharper 

Let me know what you think about the layout. It deviates a bit from the new template. It's a hybrid between what we already have and the "how to change configurations" section in the new template. Is this workable/useful?

~I'd like to get your feedback before requesting tech review from an engineer or PM.~

On second thought, I think it would help to get some feedback from @mcocapiza too.

**Comment by mcocapiza** [comment]
Hi @jeff-matthews , I think this PR is not correct because you based on an obsolete draft documentation... I've just added a comment into the Jira ticket [USF-1327](https://jira.corp.adobe.com/browse/USF-1327) and I've sent you a DM via slack giving more details.

**Review by bdenham — APPROVED** [review]
Looks good to me for now. I can see possible tweaks soon, but need to get feedback from devs first.

**Comment by jeff-matthews** [comment]
I'm going to rewrite this based on feedback from the developers. There are several containers for checkout; not just one.

**Comment by jeff-matthews** [comment]
I pushed changes for the additional containers except `ShippingForm`, `BillingForm`, and `BillToShipping` since the dev team indicated those might be removed.

I still have some work to do. I updated the TODO list in the PR description accordingly.

**Comment by jeff-matthews** [comment]
See #71

**Pull request closed without merging**
