### PR TITLE
fix: redirect orphaned pages

### PR DESCRIPTION
**Pull request by jeff-matthews**
This pull request (PR) configures a [redirect](https://docs.astro.build/en/guides/routing/#redirects) for an orphaned HTML page (page is no longer in source).

**This page**: https://experienceleague.adobe.com/developer/commerce/storefront/dropins/

**Should redirect to**: https://experienceleague.adobe.com/developer/commerce/storefront/dropins/all/introduction/

There may be other pages that require redirects.

>[!NOTE]
>It appears that you must prepend the destination with the `base` as described here: https://github.com/withastro/astro/issues/7774

### CODE REVIEW

**Comment by jeff-matthews** [comment]
I found a couple more pages that look like they need to be redirected:

- https://experienceleague.adobe.com/developer/commerce/storefront/references/requirements/
- https://experienceleague.adobe.com/developer/commerce/storefront/references/configurations/

They should redirect to:

- https://experienceleague.adobe.com/developer/commerce/storefront/get-started/requirements/
- https://experienceleague.adobe.com/developer/commerce/storefront/get-started/configurations/

**Comment by jeff-matthews** [comment]
I actually found several more pages that have been moved, but are still on production. I'm going to close this PR while I identify all of them and add the proper redirects. I'll open a new PR when I'm finished.

**Comment by jeff-matthews** [comment]
I don't know why, but the old `customize/` redirect URLs fail during build so I commented them out for now. I tested all other redirects using the `build:prod` and `preview:prod` commands locally. Even without the `customize/` redirects, I think this is an improvement in eliminating the ghost page experience.

In addition to the redirects, I also need to investigate the deployment logic to ensure that orphaned HTML files are being purged properly.

**Review by bdenham — APPROVED** [review]
Looks good, @jeff-matthews! 

I fixed the `/customize` redirects by removing the colons from within the parentheses of the redirect keys.

**Comment by jeff-matthews** [comment]
Thanks @bdenham! I feel silly for missing that detail 🫤

**Pull request merged**
